import {uiConstants} from '../Assets/uiConstants';
export const state = [
  uiConstants.assam,
  uiConstants.andraPradesh,
  uiConstants.arunachalPradesh,
  uiConstants.bihar,
  uiConstants.chhattishgarh,
  uiConstants.delhi,
  uiConstants.goa,
  uiConstants.gujrat,
  uiConstants.haryana,
  uiConstants.himachalPradesh,
  uiConstants.jk,
  uiConstants.jharkhand,
  uiConstants.karnataka,
  uiConstants.kerala,
  uiConstants.mp,
  uiConstants.maharashtra,
  uiConstants.manipur,
  uiConstants.meghalaya,
  uiConstants.mizoram,
  uiConstants.nagaland,
  uiConstants.odisha,
  uiConstants.punjab,
  uiConstants.rajasthan,
  uiConstants.sikkim,
  uiConstants.tamilNadu,
  uiConstants.telangana,
  uiConstants.tripura,
  uiConstants.up,
  uiConstants.uttarakhand,
  uiConstants.wb,
];
export const addressType = [uiConstants.office, uiConstants.hom];
