export const uiConstants = {
  buyNow: 'Buy Now',
  addToCart: 'Add to Cart',
  addedToCart: 'Added to Cart',
  toastAddedToCart: 'Product already added to cart',
  toastAddToCart: 'Product added to cart successfully',
  productDetailsPage: 'ProductDetailsPage',
  quantity: 'Amount',
  rating: 'RATING',
  custom: 'custom',
  rupeeSign: '\u20B9',
  center: 'center',
  solid: 'solid',
  hundredpercent: '100%',
  minus: '_',
  plus: '+',
  forgotYourPassword: 'Forgot Your Password?',
  helloAgain: 'Hello Again',
  welcome: 'Welcome',
  back: 'Back',
  signup: 'SIGN UP',
  alreadyAMemberLogin: 'Already a member? Log In',
  wel: 'Welcome!',
  signupToGetStarted: 'Signup to get started',
  getStarted: 'Get Started',
  iAlreadyHaveAnAccount: 'I Already Have An Account',
  userNameAlert: 'UserName must be 8-20 characters long',
  newUserNameAlert: 'Please provide a username',
  invalidUserNameAlert: 'Invalid UserName',
  emailAlert: 'Please provide email',
  invalidEmailAlert: 'Invalid email',
  passwordAlert: 'Please provide a password',
  invalidPasswordAlert: 'Invalid password',
  confirmPasswordAlert: 'Please provide a password',
  invalidConfirmpPsswordAlert: 'Passwords do not match',
  neuBuy: 'NeuBuy',
  signUpSuccessfullAlert: 'SignUp successful',
  okAlert: 'OK',
  invalidCrdential: 'Enter Valid Credentials',
  passwordEmailAlert: 'Please provide email and password',
  favoriteScreen: 'FavoriteScreen',
  discover: 'Discover',
  description: 'Fashion is all about beauty',
  clothing: 'Clothing',
  topNavigator: 'TopNavigator',
  homeScreen: 'HomeScreen',
  home: 'home',
  profileScreenName: 'Profile_Screen',
  user: 'user',
  favoriteScreenName: 'Favorite_Screen',
  heart: 'heart',
  emailAddress: 'Email Address',
  password: 'Password',
  landingPage: 'LandingPage',
  forgot: 'Forgot',
  login: 'LOG IN',
  name: 'Name',
  newConfirmPassword: 'Confirm Password',
  emptyString: '',
  loginPage: 'Login',
  newLine: '\n',
  signUpPage: 'SignUp',
  welcomePage: 'Welcomepage',
  placeHolder: 'placeholder',
  splashScreen: 'SplashScreen',
  loginText: 'Login',
  headerText: 'My Account',
  loginInfoText: 'Edit Login Information',
  addText: 'Manage Addresses',
  ordersText: 'My Orders',
  signOutText: 'Sign Out',
  myCartPage: 'MyCartPage',
  cart: 'cart',
  save: 'SAVE',
  addAddress: 'Add Address',
  fullName: 'Full Name',
  mobileNumber: 'Mobile Number',
  pincode: 'Pincode',
  fullAddress: 'Full Address',
  landmark: 'Landmark',
  assam: 'Assam',
  andraPradesh: 'Andhra Pradesh',
  arunachalPradesh: 'Arunachal Pradesh',
  bihar: 'Bihar',
  chhattishgarh: 'Chhattisgarh',
  delhi: 'Delhi',
  goa: 'Goa',
  gujrat: 'Gujarat',
  haryana: 'Haryana',
  himachalPradesh: 'Himachal Pradesh',
  jk: 'Jammu and Kashmir',
  jharkhand: 'Jharkhand',
  karnataka: 'Karnataka',
  kerala: 'Kerala',
  mp: 'Madhya Pradesh',
  maharashtra: 'Maharashtra',
  manipur: 'Manipur',
  meghalaya: 'Meghalaya',
  mizoram: 'Mizoram',
  nagaland: 'Nagaland',
  odisha: 'Odisha',
  punjab: 'Punjab',
  rajasthan: 'Rajasthan',
  sikkim: 'Sikkim',
  tamilNadu: 'Tamil Nadu',
  telangana: 'Telangana',
  tripura: 'Tripura',
  up: 'Uttar Pradesh',
  uttarakhand: 'Uttarakhand',
  wb: 'West Bengal',
  office: 'Office',
  hom: 'Home',
  nameAlert: '! Please enter valid name',
  mobileNumberAlert: 'Please enter valid mobile number',
  phnoAlert: 'Please enter valid mobile number',
  pincodeAlert: 'Please enter valid pincode',
  pinAlert: 'Pincode must be 6 digit long',
  fullAddressAlert: 'Please enter your full address',
  landmarkAlert: 'Please enter your landmark',
  stateAlert: 'Please select your state',
  addressTypeAlert: 'Please select your address type',
  addressPage: 'AddressPage',
  addAddressPage: 'AddAddressPage',
  state: 'Select State',
  addressType: 'Address Type',
  cartPage: 'cartpage',
  neuBuyText: 'NeuBuy',
  saveAddressText: 'Save',
  addNewAddressText: 'Add',
  addAddressesHeaderText: 'My Addresses',
  addressText: 'Address',
  search: 'Search',
  homeNestedScreens: 'HomeNestedScreens',
  profileNestedScreens: 'ProfileNestedScreens',
  welcomeText: 'Welcome!',
  signupText: 'Signup to get started',
  addAddressText: 'Add New Address',
  invalidCredentialText: 'Invalid Credentials',
  checkoutPage: 'Checkout Page',
  chooseAddress: 'Choose Address',
  usernameAlert: 'Please Enter Name ',
  cardAlert: '! Please Enter 16 Card Digit',
  expiryAlert: '! Please Enter Valid details.',
  cvvAlert: '! Please Enter 3 Digit CVV',
  neuBuyOrder: 'Ordered Placed Successfully',
  cardNumber: 'Card Number',
  expiry: 'MM/YYYY',
  cvv: 'CVV',
  popUpHeaderText: 'Update Your Profile Picture',
  cameraText: 'Take Photo from Camera',
  gallaryText: 'Choose From Gallary',
  imageUrl:
    'https://i.stack.imgur.com/l60Hf.png',
  existingEmailAlert: 'Email already registered. Please login ',
  existingUsernameAlert: 'Username already registered. Please login ',
  existingUsernameAndEmailAlert:
    'Username and Email already registered. Please login ',
  imageLink: 'imagelink',
  proceedToBuy: 'Proceed to Buy',
  emptyValue: null,
  shoppingCart: 'Shopping Cart',
  totalAmount: 'Sub Total:',
  selectShippingAddress: 'Select Address',
  payment: 'Payment',
  cardOptions: 'Credit/Debit Card',
  checkout: 'Checkout',
  homeScreenText: 'HomeScreen',
  cancelText: 'Cancel',
  addressNotSelectedText: 'Address Not Selected',
  checkoutText: 'Checkout',
  paymentText: 'Payment',
  creditCardText: 'Credit/Debit Card',
  cartEmptyText: 'Cart is empty \nPlease add items to buy',
  newAddressText:'Add New Address ',
  addressesText:'addresses',
  myOrder:'MyOrders',
  myOrders:'My Orders',
  orderNumber:'Order Number',
  orderDate:'Order Date',
  qty:'Qty:',
  billing:'Billing',
  addresses:'addresses',
  priceText:'AMOUNT',
  emptyCartText:'Cart is Empty',
  delItem:'Do you want to remove the item from cart ?',
  delAddress:'Do you want to delete this address ?',
  noAddressText:'No Address saved',
};
